spring:
  datasource:
     url: jdbc:mysql://localhost:3306/orderdb
     username: root
     password: root
  jpa:
    hibernate:
      ddl-auto: update
      
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  application:
    name: ORDER-SERVICE
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-86597411.okta.com/oauth2/default
#      client:
#        registration:
#          internal-client:
#            provider: okta
#            authorization-grant-type: client_credentials
#            scope: internal
#            client-id: 
#            client-secret: 
#        provider:
#          okta:
#           issuer-uri: https://dev-86597411.okta.com/oauth2/default
#                
server:
  port: 8082
eureka:
 instance:
    hostname: localhost
 client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
     defaultZone: http://localhost:8761/eureka/
#okta:
#  oauth2:
#    issuer: https://dev-86597411.okta.com/oauth2/default
#    audience: api://default
    